services:
  web:
    build: .
    ports:
      - "3000:3000"  
    environment:
      - NODE_ENV=development 
    volumes:
      - .:/app               
      - /app/node_modules    
    command: ["yarn", "dev"] 
    restart: unless-stopped

# services:
#   web:
#     build: .
#     ports:
#       - "3000:3000"  
#     environment:
#       - NODE_ENV=production 
#     volumes:
#       - /app/node_modules  # Keep only necessary volume
#     command: ["yarn", "start"]  # Run production build
#     restart: unless-stopped
